### PR TITLE
Reimplement the internal oracle price bookkeeping

### PR DESCRIPTION
**Pull request by vvp**
The current smart contracts optimize the storage for `roundId` received from Chainlink oracles from uint80 to uint64 . However, contracts can only query historical values for that `roundId` via Chainlink AggregatorProxies, which [encode their internal `phaseId` into the `roundId`](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.7/dev/AggregatorProxy.sol#L340-L342) in a way that in real production environments the querying of `currentStake` and closing of positions in `modifyStakes` practically always revert. 

As the closer examination of Chainlink behavior revealed, our previous assumption of `roundId`s being sequential does not hold either, which means that simply removing that unfortunate optimization is not enough. Therefore this PR reimplements the internal oracle price bookkeeping to use snapshot prices.

### CODE REVIEW

**Comment by microbecode** [comment]
Did I understand correctly that the aim of this PR is to revert the changes from PR https://github.com/vanilladefi/juicenet-contracts/pull/9 ?

**Comment by vvp** [comment]
> the aim of this PR is to revert the changes from PR https://github.com/vanilladefi/juicenet-contracts/pull/9 ?

Functionally yes, along with the necessary migration logic to fix the onchain state during upgrade as well. 

That said, I chose not to simply revert the code back to the old revision. Instead I refactored the contract structure from a single JuiceStaking-contract holding both state and logic to an abstract JuiceStaking-contract holding only the state and JuiceStaking02-contract inheriting it and implementing the logic. This was because we cannot override the old onchain state anymore, and this new structure makes it (hopefully) more explicit. Unfortunately this refactoring admittedly complicates the code review ... sorry about that :sweat_smile:

**Review by microbecode — APPROVED** [review]
With a very cursory look, didn't find anything wrong.

**Review by JaniAnttonen — APPROVED** [review]
Dem tests. :+1:

**Comment by vvp** [comment]
Thanks for the review :partying_face: merging now

**Pull request merged**
